version: '3.8'

services:
  tienda:
    build:
      context: .
      dockerfile: Dockerfile.tienda
    ports:
      - "5000:5000"
    depends_on:
      - banco

  banco:
    build:
      context: .
      dockerfile: Dockerfile.banco
    ports:
      - "5001:5001"
