# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shop_pb2 as shop__pb2


class ShopServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PurchaseItem = channel.unary_unary(
                '/shop.ShopService/PurchaseItem',
                request_serializer=shop__pb2.PurchaseRequest.SerializeToString,
                response_deserializer=shop__pb2.PurchaseResponse.FromString,
                )
        self.MakePayment = channel.unary_unary(
                '/shop.ShopService/MakePayment',
                request_serializer=shop__pb2.PaymentRequest.SerializeToString,
                response_deserializer=shop__pb2.PaymentResponse.FromString,
                )
        self.PlaceOrder = channel.unary_unary(
                '/shop.ShopService/PlaceOrder',
                request_serializer=shop__pb2.OrderRequest.SerializeToString,
                response_deserializer=shop__pb2.OrderResponse.FromString,
                )


class ShopServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PurchaseItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PurchaseItem': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseItem,
                    request_deserializer=shop__pb2.PurchaseRequest.FromString,
                    response_serializer=shop__pb2.PurchaseResponse.SerializeToString,
            ),
            'MakePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePayment,
                    request_deserializer=shop__pb2.PaymentRequest.FromString,
                    response_serializer=shop__pb2.PaymentResponse.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=shop__pb2.OrderRequest.FromString,
                    response_serializer=shop__pb2.OrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shop.ShopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShopService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PurchaseItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shop.ShopService/PurchaseItem',
            shop__pb2.PurchaseRequest.SerializeToString,
            shop__pb2.PurchaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MakePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shop.ShopService/MakePayment',
            shop__pb2.PaymentRequest.SerializeToString,
            shop__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shop.ShopService/PlaceOrder',
            shop__pb2.OrderRequest.SerializeToString,
            shop__pb2.OrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
